encoder:
  - in_channels: 3
    out_channels: 32
    kernel_size: 7
    heads: 8
    load_graph: graphs/nodes_5_seed_42
  - in_channels: 32
    out_channels: 64
    kernel_size: 5
    heads: 8
    load_graph: graphs/nodes_5_seed_42
  - in_channels: 64
    out_channels: 128
    kernel_size: 3
    heads: 8
    load_graph: graphs/nodes_5_seed_42
  - in_channels: 128
    out_channels: 256
    kernel_size: 3
    heads: 8
    load_graph: graphs/nodes_5_seed_42
  - in_channels: 256
    out_channels: 512
    kernel_size: 3
    heads: 8
    load_graph: graphs/nodes_5_seed_42

decoder:
  - in_channels: 512
    feature_in_channels: 256
    skip_in_channels: 512
    upsample_channels: 128
    out_channels: 256
    skip_out_channels: 512
    concat_disp: false
    calculate_disp: false
  - in_channels: 256
    feature_in_channels: 128
    skip_in_channels: 512
    upsample_channels: 64
    out_channels: 256
    skip_out_channels: 256
    concat_disp: false
    calculate_disp: true
  - in_channels: 256
    feature_in_channels: 64
    skip_in_channels: 256
    upsample_channels: 64
    out_channels: 128
    skip_out_channels: 128
    concat_disp: true
    calculate_disp: true
  - in_channels: 128
    feature_in_channels: 32
    skip_in_channels: 128
    upsample_channels: 16
    out_channels: 64
    skip_out_channels: 64
    concat_disp: true
    calculate_disp: true
  - in_channels: 64
    feature_in_channels: 3
    skip_in_channels: 64
    upsample_channels: 8
    out_channels: 32
    skip_out_channels: 32
    concat_disp: true
    calculate_disp: true

discriminator:
  pyramid-layers:
    - in_channels: 6
      out_channels: 32
      kernel_size: 7
      heads: 8
      load_graph: graphs/nodes_5_seed_42
    - in_channels: 38
      out_channels: 64
      kernel_size: 5
      heads: 8
      load_graph: graphs/nodes_5_seed_42
    - in_channels: 70
      out_channels: 128
      kernel_size: 3
      heads: 8
      load_graph: graphs/nodes_5_seed_42
    - in_channels: 134
      out_channels: 256
      kernel_size: 3
      heads: 8
      load_graph: graphs/nodes_5_seed_42
  post-pyramid-layers:
    - in_channels: 256
      out_channels: 256
      kernel_size: 3
      heads: 8
      load_graph: graphs/nodes_5_seed_42
  linear-layer:
    in_features: 32768