model:
  encoder:
    load_graph: graphs/nodes_5_seed_42
    nodes: 5
    seed: 42
    layers:
      - in_channels: 3
        out_channels: 32
        kernel_size: 7
        heads: 8
      - in_channels: 32
        out_channels: 64
        kernel_size: 5
        heads: 8
      - in_channels: 64
        out_channels: 128
        kernel_size: 3
        heads: 8
      - in_channels: 128
        out_channels: 256
        kernel_size: 3
        heads: 8
      - in_channels: 256
        out_channels: 512
        kernel_size: 3
        heads: 8

  decoder:
    layers:
      - in_channels: 512
        feature_in_channels: 256
        skip_in_channels: 512
        upsample_channels: 128
        out_channels: 256
        skip_out_channels: 512
        concat_disp: false
        calculate_disp: false
      - in_channels: 256
        feature_in_channels: 128
        skip_in_channels: 512
        upsample_channels: 64
        out_channels: 256
        skip_out_channels: 256
        concat_disp: false
        calculate_disp: true
        disp_channels: 4
      - in_channels: 256
        feature_in_channels: 64
        skip_in_channels: 256
        upsample_channels: 32
        out_channels: 128
        skip_out_channels: 128
        concat_disp: true
        calculate_disp: true
        disp_channels: 4
      - in_channels: 128
        feature_in_channels: 32
        skip_in_channels: 128
        upsample_channels: 16
        out_channels: 64
        skip_out_channels: 64
        concat_disp: true
        calculate_disp: true
        disp_channels: 4
      - in_channels: 64
        feature_in_channels: 3
        skip_in_channels: 64
        upsample_channels: 8
        out_channels: 32
        skip_out_channels: 32
        concat_disp: true
        calculate_disp: true
        disp_channels: 4

discriminator:
  load_graph: graphs/nodes_5_seed_42
  nodes: 5
  seed: 42
  layers:
    - in_channels: 6
      out_channels: 32
      kernel_size: 7
      heads: 8
    - in_channels: 38
      out_channels: 64
      kernel_size: 5
      heads: 8
    - in_channels: 70
      out_channels: 128
      kernel_size: 3
      heads: 8
    - in_channels: 134
      out_channels: 256
      kernel_size: 3
      heads: 8
  final_conv:
      in_channels: 256
      out_channels: 256
      kernel_size: 3
      heads: 8
  linear_in_features: 32768

loss:
  wssim_weight: 1.0
  consistency_weight: 1.0
  smoothness_weight: 1.0
  adversarial_weight: 0.85
  perceptual_weight: 0.05
  predictive_error_weight: 1.0
  wssim_alpha: 0.85
  perceptual_start: 5
  adversarial_loss_type: mse
  error_loss_config:
    loss_type: l1
    smoothness_weight: 0
    consistency_weight: 0.5
    pooling: false
    include_aleatoric: false
